version: "3.8"
services:
  faeNeMo:
    build: ./
    command: script -c 'python -m pip install tensorboardX crc32c soundfile && tensorboard --logdir=/workspace/nemo/nemo_experiments/ & /workspace/nemo/start-jupyter.sh' -f /dev/stdout
    image: nemo/fae/cv22:latest
    network_mode: host
    volumes:
      - ${PATH_NEMO_EXPERIMENTS}:/workspace/nemo/nemo_experiments # nemo-experiments (space shared with other contributors)
      - ${PATH_CV_CORPORA}:/corpora:ro
    ports:
      - ${PORT_JUPY}:8888 # this is jupyter notebook
      - ${PORT_TBRD}:6006 # tensorboard
    networks:
      - interactions
    restart: always
