version: "3.8"
services:
  myNeMo:
    build: ./
    command: script -c 'python -m pip install tensorboardX crc32c soundfile && tensorboard --logdir=${PATH_NEMO_EXPERIMENTS}/ & /workspace/nemo/start-jupyter.sh' -f /dev/stdout
    image: NeMo/fae/cv22:latest
    volumes:
      - ${PATH_LDC}:/n/LDC/:ro # this exposes the corpora as read-only
      - ${PATH_CORPORA}:/n/corpora/:ro # this exposes the corpora as read-only
      - ${PATH_NEMO_EXPERIMENTS}:/data/nemo_experiments # nemo-experiments (space shared with other contributors)
    ports:
      - ${PORT_JUPY}:8888 # this is jupyter notebook
      - ${PORT_TBRD}:6006 # tensorboard
    networks:
      - interactions
    restart: always

networks:
  interactions:
    driver: bridge
    name: interactions
    ipam:
      driver: default
      config:
        - subnet: 172.19.58.0/24
